
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package palamod.init;

import palamod.block.XpbushonBlock;
import palamod.block.XpbushBlock;
import palamod.block.WoddenspikeBlock;
import palamod.block.TrxiumoreBlock;
import palamod.block.TrxiumblockBlock;
import palamod.block.TruetresureBlock;
import palamod.block.TrixiumnbtblockBlock;
import palamod.block.TitanestairsBlock;
import palamod.block.TitanespikeBlock;
import palamod.block.TitaneslabBlock;
import palamod.block.TitaneOreBlock;
import palamod.block.TitaneBlockBlock;
import palamod.block.Tcv2Block;
import palamod.block.StonyBlock;
import palamod.block.SpikegoldBlock;
import palamod.block.SlimepadBlock;
import palamod.block.RenforcedobsidianBlock;
import palamod.block.PalalavaBlock;
import palamod.block.PaladiumstairsBlock;
import palamod.block.PaladiumspikeBlock;
import palamod.block.PaladiumslabBlock;
import palamod.block.PaladiummachineBlock;
import palamod.block.PaladiumfurnaceonBlock;
import palamod.block.PaladiumfurnaceBlock;
import palamod.block.PaladiumforgeBlock;
import palamod.block.PaladiumcrusherBlock;
import palamod.block.PaladiumOreBlock;
import palamod.block.PaladiumGreenoreBlock;
import palamod.block.PaladiumGreenblockBlock;
import palamod.block.PaladiumBlockBlock;
import palamod.block.OstryasapplingBlock;
import palamod.block.Ostrya_woodWoodBlock;
import palamod.block.Ostrya_woodStairsBlock;
import palamod.block.Ostrya_woodSlabBlock;
import palamod.block.Ostrya_woodPlanksBlock;
import palamod.block.Ostrya_woodLogBlock;
import palamod.block.Ostrya_woodLeavesBlock;
import palamod.block.Ostrya_woodFenceGateBlock;
import palamod.block.Ostrya_woodFenceBlock;
import palamod.block.Orangeblue4Block;
import palamod.block.Orangeblue3Block;
import palamod.block.Orangeblue2Block;
import palamod.block.Orangeblue1Block;
import palamod.block.Orangeblue0Block;
import palamod.block.ObsidiantrapdoorBlock;
import palamod.block.ObsidiandoorBlock;
import palamod.block.NbtblockBlock;
import palamod.block.MegasafechestBlock;
import palamod.block.LuckyblockBlock;
import palamod.block.Loadblock1tBlock;
import palamod.block.LavaobsidianBlock;
import palamod.block.Kiwano4Block;
import palamod.block.Kiwano3Block;
import palamod.block.Kiwano2Block;
import palamod.block.Kiwano1Block;
import palamod.block.Kiwano0Block;
import palamod.block.JudeecercissapplingBlock;
import palamod.block.JudeecercisdoorBlock;
import palamod.block.Judeecercis_WoodBlock;
import palamod.block.Judeecercis_StairsBlock;
import palamod.block.Judeecercis_SlabBlock;
import palamod.block.Judeecercis_PlanksBlock;
import palamod.block.Judeecercis_LogBlock;
import palamod.block.Judeecercis_LeavesBlock;
import palamod.block.Judeecercis_FenceGateBlock;
import palamod.block.Judeecercis_FenceBlock;
import palamod.block.JacarandasapplingBlock;
import palamod.block.Jacaranda_WoodBlock;
import palamod.block.Jacaranda_StairsBlock;
import palamod.block.Jacaranda_SlabBlock;
import palamod.block.Jacaranda_PlanksBlock;
import palamod.block.Jacaranda_LogBlock;
import palamod.block.Jacaranda_LeavesBlock;
import palamod.block.Jacaranda_FenceGateBlock;
import palamod.block.Jacaranda_FenceBlock;
import palamod.block.IronspikeBlock;
import palamod.block.GuardianblockBlock;
import palamod.block.GrinderframeBlock;
import palamod.block.GrindercasingBlock;
import palamod.block.GrinderblockBlock;
import palamod.block.GreenpaladiumstairsBlock;
import palamod.block.GreenpaladiumslabBlock;
import palamod.block.FindiumstairsBlock;
import palamod.block.FindiumslabBlock;
import palamod.block.FindiumOreBlock;
import palamod.block.FindiumBlockBlock;
import palamod.block.FalsetresureBlock;
import palamod.block.FakewaterobsidianBlock;
import palamod.block.FakewaterBlock;
import palamod.block.FakepaladiumoreBlock;
import palamod.block.FactionblckBlock;
import palamod.block.ErablesapplingBlock;
import palamod.block.Erable_WoodBlock;
import palamod.block.Erable_StairsBlock;
import palamod.block.Erable_SlabBlock;
import palamod.block.Erable_PlanksBlock;
import palamod.block.Erable_LogBlock;
import palamod.block.Erable_LeavesBlock;
import palamod.block.Erable_FenceGateBlock;
import palamod.block.Erable_FenceBlock;
import palamod.block.EndiumstairsBlock;
import palamod.block.EndiumslabBlock;
import palamod.block.EndiumnuggetoreBlock;
import palamod.block.EndiumluckyblockBlock;
import palamod.block.EndiumBlockBlock;
import palamod.block.ElevatorwhiteBlock;
import palamod.block.ElevatorredBlock;
import palamod.block.ElevatorpurpleBlock;
import palamod.block.ElevatorpinkBlock;
import palamod.block.ElevatororangeBlock;
import palamod.block.ElevatorlightgreenBlock;
import palamod.block.ElevatorlightgrayBlock;
import palamod.block.ElevatorlightblueBlock;
import palamod.block.ElevatorgreenBlock;
import palamod.block.ElevatorgrayBlock;
import palamod.block.ElevatorcyanBlock;
import palamod.block.ElevatorbrownBlock;
import palamod.block.ElevatorblueBlock;
import palamod.block.Eggplant3Block;
import palamod.block.Eggplant2Block;
import palamod.block.Eggplant1Block;
import palamod.block.Eggplant0Block;
import palamod.block.DiamondspikeBlock;
import palamod.block.CrownBlock;
import palamod.block.Contructedgrinderlayer2Block;
import palamod.block.Contructedgrinderlayer1Block;
import palamod.block.CompactedobsidianBlock;
import palamod.block.ColoredlampBlock;
import palamod.block.ColofullampBlock;
import palamod.block.CloudblockBlock;
import palamod.block.Chervil3Block;
import palamod.block.Chervil2Block;
import palamod.block.Chervil1Block;
import palamod.block.Chervil0Block;
import palamod.block.BlackluckyblockBlock;
import palamod.block.AsemblingtableBlock;
import palamod.block.AngelicwaterBlock;
import palamod.block.AmetystespikeBlock;
import palamod.block.AmethyststairsBlock;
import palamod.block.AmethystslabBlock;
import palamod.block.AmethysteOreBlock;
import palamod.block.AmethysteBlockBlock;
import palamod.block.Alchimet1Block;
import palamod.block.AlarmBlock;

import palamod.PalamodMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

public class PalamodModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, PalamodMod.MODID);
	public static final RegistryObject<Block> PALADIUM_ORE = REGISTRY.register("paladium_ore", () -> new PaladiumOreBlock());
	public static final RegistryObject<Block> PALADIUM_BLOCK = REGISTRY.register("paladium_block", () -> new PaladiumBlockBlock());
	public static final RegistryObject<Block> PALADIUMSTAIRS = REGISTRY.register("paladiumstairs", () -> new PaladiumstairsBlock());
	public static final RegistryObject<Block> PALADIUMSLAB = REGISTRY.register("paladiumslab", () -> new PaladiumslabBlock());
	public static final RegistryObject<Block> TITANE_ORE = REGISTRY.register("titane_ore", () -> new TitaneOreBlock());
	public static final RegistryObject<Block> TITANE_BLOCK = REGISTRY.register("titane_block", () -> new TitaneBlockBlock());
	public static final RegistryObject<Block> TITANESTAIRS = REGISTRY.register("titanestairs", () -> new TitanestairsBlock());
	public static final RegistryObject<Block> TITANESLAB = REGISTRY.register("titaneslab", () -> new TitaneslabBlock());
	public static final RegistryObject<Block> AMETHYSTE_ORE = REGISTRY.register("amethyste_ore", () -> new AmethysteOreBlock());
	public static final RegistryObject<Block> AMETHYSTE_BLOCK = REGISTRY.register("amethyste_block", () -> new AmethysteBlockBlock());
	public static final RegistryObject<Block> AMETHYSTSTAIRS = REGISTRY.register("amethyststairs", () -> new AmethyststairsBlock());
	public static final RegistryObject<Block> AMETHYSTSLAB = REGISTRY.register("amethystslab", () -> new AmethystslabBlock());
	public static final RegistryObject<Block> PALADIUMCRUSHER = REGISTRY.register("paladiumcrusher", () -> new PaladiumcrusherBlock());
	public static final RegistryObject<Block> ENDIUM_BLOCK = REGISTRY.register("endium_block", () -> new EndiumBlockBlock());
	public static final RegistryObject<Block> PALADIUM_GREENORE = REGISTRY.register("paladium_greenore", () -> new PaladiumGreenoreBlock());
	public static final RegistryObject<Block> PALADIUM_GREENBLOCK = REGISTRY.register("paladium_greenblock", () -> new PaladiumGreenblockBlock());
	public static final RegistryObject<Block> FINDIUM_ORE = REGISTRY.register("findium_ore", () -> new FindiumOreBlock());
	public static final RegistryObject<Block> FINDIUM_BLOCK = REGISTRY.register("findium_block", () -> new FindiumBlockBlock());
	public static final RegistryObject<Block> FINDIUMSTAIRS = REGISTRY.register("findiumstairs", () -> new FindiumstairsBlock());
	public static final RegistryObject<Block> FINDIUMSLAB = REGISTRY.register("findiumslab", () -> new FindiumslabBlock());
	public static final RegistryObject<Block> TRXIUMORE = REGISTRY.register("trxiumore", () -> new TrxiumoreBlock());
	public static final RegistryObject<Block> TRXIUMBLOCK = REGISTRY.register("trxiumblock", () -> new TrxiumblockBlock());
	public static final RegistryObject<Block> XPBUSH = REGISTRY.register("xpbush", () -> new XpbushBlock());
	public static final RegistryObject<Block> SLIMEPAD = REGISTRY.register("slimepad", () -> new SlimepadBlock());
	public static final RegistryObject<Block> ALCHIMET_1 = REGISTRY.register("alchimet_1", () -> new Alchimet1Block());
	public static final RegistryObject<Block> ASEMBLINGTABLE = REGISTRY.register("asemblingtable", () -> new AsemblingtableBlock());
	public static final RegistryObject<Block> PALADIUMFURNACE = REGISTRY.register("paladiumfurnace", () -> new PaladiumfurnaceBlock());
	public static final RegistryObject<Block> CONTRUCTEDGRINDERLAYER_1 = REGISTRY.register("contructedgrinderlayer_1",
			() -> new Contructedgrinderlayer1Block());
	public static final RegistryObject<Block> CONTRUCTEDGRINDERLAYER_2 = REGISTRY.register("contructedgrinderlayer_2",
			() -> new Contructedgrinderlayer2Block());
	public static final RegistryObject<Block> OBSIDIANTRAPDOOR = REGISTRY.register("obsidiantrapdoor", () -> new ObsidiantrapdoorBlock());
	public static final RegistryObject<Block> RENFORCEDOBSIDIAN = REGISTRY.register("renforcedobsidian", () -> new RenforcedobsidianBlock());
	public static final RegistryObject<Block> OBSIDIANDOOR = REGISTRY.register("obsidiandoor", () -> new ObsidiandoorBlock());
	public static final RegistryObject<Block> COMPACTEDOBSIDIAN = REGISTRY.register("compactedobsidian", () -> new CompactedobsidianBlock());
	public static final RegistryObject<Block> FAKEWATEROBSIDIAN = REGISTRY.register("fakewaterobsidian", () -> new FakewaterobsidianBlock());
	public static final RegistryObject<Block> FAKEWATER = REGISTRY.register("fakewater", () -> new FakewaterBlock());
	public static final RegistryObject<Block> PALALAVA = REGISTRY.register("palalava", () -> new PalalavaBlock());
	public static final RegistryObject<Block> ANGELICWATER = REGISTRY.register("angelicwater", () -> new AngelicwaterBlock());
	public static final RegistryObject<Block> LAVAOBSIDIAN = REGISTRY.register("lavaobsidian", () -> new LavaobsidianBlock());
	public static final RegistryObject<Block> WODDENSPIKE = REGISTRY.register("woddenspike", () -> new WoddenspikeBlock());
	public static final RegistryObject<Block> IRONSPIKE = REGISTRY.register("ironspike", () -> new IronspikeBlock());
	public static final RegistryObject<Block> SPIKEGOLD = REGISTRY.register("spikegold", () -> new SpikegoldBlock());
	public static final RegistryObject<Block> DIAMONDSPIKE = REGISTRY.register("diamondspike", () -> new DiamondspikeBlock());
	public static final RegistryObject<Block> AMETYSTESPIKE = REGISTRY.register("ametystespike", () -> new AmetystespikeBlock());
	public static final RegistryObject<Block> TITANESPIKE = REGISTRY.register("titanespike", () -> new TitanespikeBlock());
	public static final RegistryObject<Block> PALADIUMSPIKE = REGISTRY.register("paladiumspike", () -> new PaladiumspikeBlock());
	public static final RegistryObject<Block> PALADIUMFORGE = REGISTRY.register("paladiumforge", () -> new PaladiumforgeBlock());
	public static final RegistryObject<Block> LOADBLOCK_1T = REGISTRY.register("loadblock_1t", () -> new Loadblock1tBlock());
	public static final RegistryObject<Block> FALSETRESURE = REGISTRY.register("falsetresure", () -> new FalsetresureBlock());
	public static final RegistryObject<Block> TRUETRESURE = REGISTRY.register("truetresure", () -> new TruetresureBlock());
	public static final RegistryObject<Block> ALARM = REGISTRY.register("alarm", () -> new AlarmBlock());
	public static final RegistryObject<Block> MEGASAFECHEST = REGISTRY.register("megasafechest", () -> new MegasafechestBlock());
	public static final RegistryObject<Block> COLOREDLAMP = REGISTRY.register("coloredlamp", () -> new ColoredlampBlock());
	public static final RegistryObject<Block> COLOFULLAMP = REGISTRY.register("colofullamp", () -> new ColofullampBlock());
	public static final RegistryObject<Block> FAKEPALADIUMORE = REGISTRY.register("fakepaladiumore", () -> new FakepaladiumoreBlock());
	public static final RegistryObject<Block> ELEVATORWHITE = REGISTRY.register("elevatorwhite", () -> new ElevatorwhiteBlock());
	public static final RegistryObject<Block> ELEVATORRED = REGISTRY.register("elevatorred", () -> new ElevatorredBlock());
	public static final RegistryObject<Block> ELEVATORBLUE = REGISTRY.register("elevatorblue", () -> new ElevatorblueBlock());
	public static final RegistryObject<Block> ELEVATORGREEN = REGISTRY.register("elevatorgreen", () -> new ElevatorgreenBlock());
	public static final RegistryObject<Block> ELEVATORPINK = REGISTRY.register("elevatorpink", () -> new ElevatorpinkBlock());
	public static final RegistryObject<Block> ELEVATORLIGHTBLUE = REGISTRY.register("elevatorlightblue", () -> new ElevatorlightblueBlock());
	public static final RegistryObject<Block> ELEVATORLIGHTGREEN = REGISTRY.register("elevatorlightgreen", () -> new ElevatorlightgreenBlock());
	public static final RegistryObject<Block> ELEVATORBROWN = REGISTRY.register("elevatorbrown", () -> new ElevatorbrownBlock());
	public static final RegistryObject<Block> ELEVATORORANGE = REGISTRY.register("elevatororange", () -> new ElevatororangeBlock());
	public static final RegistryObject<Block> ELEVATORPURPLE = REGISTRY.register("elevatorpurple", () -> new ElevatorpurpleBlock());
	public static final RegistryObject<Block> ELEVATORGRAY = REGISTRY.register("elevatorgray", () -> new ElevatorgrayBlock());
	public static final RegistryObject<Block> ELEVATORLIGHTGRAY = REGISTRY.register("elevatorlightgray", () -> new ElevatorlightgrayBlock());
	public static final RegistryObject<Block> ELEVATORCYAN = REGISTRY.register("elevatorcyan", () -> new ElevatorcyanBlock());
	public static final RegistryObject<Block> GUARDIANBLOCK = REGISTRY.register("guardianblock", () -> new GuardianblockBlock());
	public static final RegistryObject<Block> STONY = REGISTRY.register("stony", () -> new StonyBlock());
	public static final RegistryObject<Block> CLOUDBLOCK = REGISTRY.register("cloudblock", () -> new CloudblockBlock());
	public static final RegistryObject<Block> GRINDERBLOCK = REGISTRY.register("grinderblock", () -> new GrinderblockBlock());
	public static final RegistryObject<Block> GRINDERCASING = REGISTRY.register("grindercasing", () -> new GrindercasingBlock());
	public static final RegistryObject<Block> GRINDERFRAME = REGISTRY.register("grinderframe", () -> new GrinderframeBlock());
	public static final RegistryObject<Block> TCV_2 = REGISTRY.register("tcv_2", () -> new Tcv2Block());
	public static final RegistryObject<Block> OSTRYASAPPLING = REGISTRY.register("ostryasappling", () -> new OstryasapplingBlock());
	public static final RegistryObject<Block> JACARANDASAPPLING = REGISTRY.register("jacarandasappling", () -> new JacarandasapplingBlock());
	public static final RegistryObject<Block> OSTRYA_WOOD_WOOD = REGISTRY.register("ostrya_wood_wood", () -> new Ostrya_woodWoodBlock());
	public static final RegistryObject<Block> OSTRYA_WOOD_LOG = REGISTRY.register("ostrya_wood_log", () -> new Ostrya_woodLogBlock());
	public static final RegistryObject<Block> OSTRYA_WOOD_PLANKS = REGISTRY.register("ostrya_wood_planks", () -> new Ostrya_woodPlanksBlock());
	public static final RegistryObject<Block> OSTRYA_WOOD_LEAVES = REGISTRY.register("ostrya_wood_leaves", () -> new Ostrya_woodLeavesBlock());
	public static final RegistryObject<Block> OSTRYA_WOOD_STAIRS = REGISTRY.register("ostrya_wood_stairs", () -> new Ostrya_woodStairsBlock());
	public static final RegistryObject<Block> OSTRYA_WOOD_SLAB = REGISTRY.register("ostrya_wood_slab", () -> new Ostrya_woodSlabBlock());
	public static final RegistryObject<Block> OSTRYA_WOOD_FENCE = REGISTRY.register("ostrya_wood_fence", () -> new Ostrya_woodFenceBlock());
	public static final RegistryObject<Block> OSTRYA_WOOD_FENCE_GATE = REGISTRY.register("ostrya_wood_fence_gate",
			() -> new Ostrya_woodFenceGateBlock());
	public static final RegistryObject<Block> JACARANDA_WOOD = REGISTRY.register("jacaranda_wood", () -> new Jacaranda_WoodBlock());
	public static final RegistryObject<Block> JACARANDA_LOG = REGISTRY.register("jacaranda_log", () -> new Jacaranda_LogBlock());
	public static final RegistryObject<Block> JACARANDA_PLANKS = REGISTRY.register("jacaranda_planks", () -> new Jacaranda_PlanksBlock());
	public static final RegistryObject<Block> JACARANDA_LEAVES = REGISTRY.register("jacaranda_leaves", () -> new Jacaranda_LeavesBlock());
	public static final RegistryObject<Block> JACARANDA_STAIRS = REGISTRY.register("jacaranda_stairs", () -> new Jacaranda_StairsBlock());
	public static final RegistryObject<Block> JACARANDA_SLAB = REGISTRY.register("jacaranda_slab", () -> new Jacaranda_SlabBlock());
	public static final RegistryObject<Block> JACARANDA_FENCE = REGISTRY.register("jacaranda_fence", () -> new Jacaranda_FenceBlock());
	public static final RegistryObject<Block> JACARANDA_FENCE_GATE = REGISTRY.register("jacaranda_fence_gate", () -> new Jacaranda_FenceGateBlock());
	public static final RegistryObject<Block> JUDEECERCIS_WOOD = REGISTRY.register("judeecercis_wood", () -> new Judeecercis_WoodBlock());
	public static final RegistryObject<Block> JUDEECERCIS_LOG = REGISTRY.register("judeecercis_log", () -> new Judeecercis_LogBlock());
	public static final RegistryObject<Block> JUDEECERCIS_PLANKS = REGISTRY.register("judeecercis_planks", () -> new Judeecercis_PlanksBlock());
	public static final RegistryObject<Block> JUDEECERCIS_LEAVES = REGISTRY.register("judeecercis_leaves", () -> new Judeecercis_LeavesBlock());
	public static final RegistryObject<Block> JUDEECERCIS_STAIRS = REGISTRY.register("judeecercis_stairs", () -> new Judeecercis_StairsBlock());
	public static final RegistryObject<Block> JUDEECERCIS_SLAB = REGISTRY.register("judeecercis_slab", () -> new Judeecercis_SlabBlock());
	public static final RegistryObject<Block> JUDEECERCIS_FENCE = REGISTRY.register("judeecercis_fence", () -> new Judeecercis_FenceBlock());
	public static final RegistryObject<Block> JUDEECERCIS_FENCE_GATE = REGISTRY.register("judeecercis_fence_gate",
			() -> new Judeecercis_FenceGateBlock());
	public static final RegistryObject<Block> ERABLE_WOOD = REGISTRY.register("erable_wood", () -> new Erable_WoodBlock());
	public static final RegistryObject<Block> ERABLE_LOG = REGISTRY.register("erable_log", () -> new Erable_LogBlock());
	public static final RegistryObject<Block> ERABLE_PLANKS = REGISTRY.register("erable_planks", () -> new Erable_PlanksBlock());
	public static final RegistryObject<Block> ERABLE_LEAVES = REGISTRY.register("erable_leaves", () -> new Erable_LeavesBlock());
	public static final RegistryObject<Block> ERABLE_STAIRS = REGISTRY.register("erable_stairs", () -> new Erable_StairsBlock());
	public static final RegistryObject<Block> ERABLE_SLAB = REGISTRY.register("erable_slab", () -> new Erable_SlabBlock());
	public static final RegistryObject<Block> ERABLE_FENCE = REGISTRY.register("erable_fence", () -> new Erable_FenceBlock());
	public static final RegistryObject<Block> ERABLE_FENCE_GATE = REGISTRY.register("erable_fence_gate", () -> new Erable_FenceGateBlock());
	public static final RegistryObject<Block> ERABLESAPPLING = REGISTRY.register("erablesappling", () -> new ErablesapplingBlock());
	public static final RegistryObject<Block> JUDEECERCISSAPPLING = REGISTRY.register("judeecercissappling", () -> new JudeecercissapplingBlock());
	public static final RegistryObject<Block> JUDEECERCISDOOR = REGISTRY.register("judeecercisdoor", () -> new JudeecercisdoorBlock());
	public static final RegistryObject<Block> PALADIUMMACHINE = REGISTRY.register("paladiummachine", () -> new PaladiummachineBlock());
	public static final RegistryObject<Block> LUCKYBLOCK = REGISTRY.register("luckyblock", () -> new LuckyblockBlock());
	public static final RegistryObject<Block> BLACKLUCKYBLOCK = REGISTRY.register("blackluckyblock", () -> new BlackluckyblockBlock());
	public static final RegistryObject<Block> NBTBLOCK = REGISTRY.register("nbtblock", () -> new NbtblockBlock());
	public static final RegistryObject<Block> XPBUSHON = REGISTRY.register("xpbushon", () -> new XpbushonBlock());
	public static final RegistryObject<Block> PALADIUMFURNACEON = REGISTRY.register("paladiumfurnaceon", () -> new PaladiumfurnaceonBlock());
	public static final RegistryObject<Block> EGGPLANT_0 = REGISTRY.register("eggplant_0", () -> new Eggplant0Block());
	public static final RegistryObject<Block> EGGPLANT_1 = REGISTRY.register("eggplant_1", () -> new Eggplant1Block());
	public static final RegistryObject<Block> EGGPLANT_2 = REGISTRY.register("eggplant_2", () -> new Eggplant2Block());
	public static final RegistryObject<Block> EGGPLANT_3 = REGISTRY.register("eggplant_3", () -> new Eggplant3Block());
	public static final RegistryObject<Block> CHERVIL_1 = REGISTRY.register("chervil_1", () -> new Chervil1Block());
	public static final RegistryObject<Block> CHERVIL_0 = REGISTRY.register("chervil_0", () -> new Chervil0Block());
	public static final RegistryObject<Block> CHERVIL_2 = REGISTRY.register("chervil_2", () -> new Chervil2Block());
	public static final RegistryObject<Block> CHERVIL_3 = REGISTRY.register("chervil_3", () -> new Chervil3Block());
	public static final RegistryObject<Block> KIWANO_4 = REGISTRY.register("kiwano_4", () -> new Kiwano4Block());
	public static final RegistryObject<Block> KIWANO_3 = REGISTRY.register("kiwano_3", () -> new Kiwano3Block());
	public static final RegistryObject<Block> KIWANO_2 = REGISTRY.register("kiwano_2", () -> new Kiwano2Block());
	public static final RegistryObject<Block> KIWANO_1 = REGISTRY.register("kiwano_1", () -> new Kiwano1Block());
	public static final RegistryObject<Block> KIWANO_0 = REGISTRY.register("kiwano_0", () -> new Kiwano0Block());
	public static final RegistryObject<Block> ORANGEBLUE_1 = REGISTRY.register("orangeblue_1", () -> new Orangeblue1Block());
	public static final RegistryObject<Block> ORANGEBLUE_0 = REGISTRY.register("orangeblue_0", () -> new Orangeblue0Block());
	public static final RegistryObject<Block> ORANGEBLUE_2 = REGISTRY.register("orangeblue_2", () -> new Orangeblue2Block());
	public static final RegistryObject<Block> ORANGEBLUE_3 = REGISTRY.register("orangeblue_3", () -> new Orangeblue3Block());
	public static final RegistryObject<Block> ORANGEBLUE_4 = REGISTRY.register("orangeblue_4", () -> new Orangeblue4Block());
	public static final RegistryObject<Block> TRIXIUMNBTBLOCK = REGISTRY.register("trixiumnbtblock", () -> new TrixiumnbtblockBlock());
	public static final RegistryObject<Block> CROWN = REGISTRY.register("crown", () -> new CrownBlock());
	public static final RegistryObject<Block> FACTIONBLCK = REGISTRY.register("factionblck", () -> new FactionblckBlock());
	public static final RegistryObject<Block> ENDIUMLUCKYBLOCK = REGISTRY.register("endiumluckyblock", () -> new EndiumluckyblockBlock());
	public static final RegistryObject<Block> ENDIUMNUGGETORE = REGISTRY.register("endiumnuggetore", () -> new EndiumnuggetoreBlock());
	public static final RegistryObject<Block> ENDIUMSLAB = REGISTRY.register("endiumslab", () -> new EndiumslabBlock());
	public static final RegistryObject<Block> ENDIUMSTAIRS = REGISTRY.register("endiumstairs", () -> new EndiumstairsBlock());
	public static final RegistryObject<Block> GREENPALADIUMSTAIRS = REGISTRY.register("greenpaladiumstairs", () -> new GreenpaladiumstairsBlock());
	public static final RegistryObject<Block> GREENPALADIUMSLAB = REGISTRY.register("greenpaladiumslab", () -> new GreenpaladiumslabBlock());
}
